/**
 * seedData.js — Seed real courses and livelihoods into MongoDB (Expanded to 30+)
 * Run: node src/scripts/seedData.js
 */
require('dotenv').config();
const mongoose = require('mongoose');
const Course = require('../models/Course');
const Livelihood = require('../models/Livelihood');

const courses = [
  // Previous 12
  { title: 'Self Employed Tailor', titleHi: 'स्व-रोज़गार दर्ज़ी', sector: 'Apparel', nsqfLevel: 4, minEducation: '5th', durationHours: 600, jobRoles: ['Tailor', 'Garment Maker', 'Boutique Owner'], tags: ['tailoring', 'sewing', 'silai', 'fashion'], sourceName: 'NSDC', verified: true },
  { title: 'Assistant Electrician', titleHi: 'सहायक बिजली मिस्त्री', sector: 'Electronics & Hardware', nsqfLevel: 3, minEducation: '8th', durationHours: 400, jobRoles: ['Electrician Helper', 'Wiring Technician'], tags: ['electrical', 'wiring', 'bijli'], sourceName: 'NSDC', verified: true },
  { title: 'Organic Farmer', titleHi: 'जैविक किसान', sector: 'Agriculture', nsqfLevel: 3, minEducation: '5th', durationHours: 300, jobRoles: ['Organic Farm Manager', 'Agriculture Worker'], tags: ['farming', 'agriculture', 'kheti', 'organic'], sourceName: 'NSDC', verified: true },
  { title: 'Beauty Therapist', titleHi: 'ब्यूटी थेरेपिस्ट', sector: 'Beauty & Wellness', nsqfLevel: 4, minEducation: '8th', durationHours: 500, jobRoles: ['Beauty Parlour Assistant', 'Makeup Artist'], tags: ['beauty', 'parlour', 'makeup', 'wellness'], sourceName: 'NSDC', verified: true },
  { title: 'Plumber General', titleHi: 'प्लंबर (सामान्य)', sector: 'Plumbing', nsqfLevel: 3, minEducation: '5th', durationHours: 400, jobRoles: ['Plumber', 'Pipe Fitter'], tags: ['plumbing', 'pipe', 'nalkoop'], sourceName: 'NSDC', verified: true },
  { title: 'Mobile Phone Hardware Repair Technician', titleHi: 'मोबाइल फोन रिपेयर तकनीशियन', sector: 'Electronics & Hardware', nsqfLevel: 4, minEducation: '10th', durationHours: 450, jobRoles: ['Mobile Repair Technician', 'Phone Service Engineer'], tags: ['mobile', 'repair', 'phone', 'hardware', 'electronics'], sourceName: 'NSDC', verified: true },
  { title: 'Dairy Farmer / Entrepreneur', titleHi: 'डेयरी किसान / उद्यमी', sector: 'Agriculture', nsqfLevel: 3, minEducation: '5th', durationHours: 300, jobRoles: ['Dairy Farmer', 'Milk Producer', 'Cattle Manager'], tags: ['dairy', 'milk', 'dudh', 'cattle', 'animal husbandry'], sourceName: 'NSDC', verified: true },
  { title: 'Computer Operator & Programming Assistant (COPA)', titleHi: 'कंप्यूटर ऑपरेटर', sector: 'IT-ITeS', nsqfLevel: 4, minEducation: '10th', durationHours: 960, jobRoles: ['Computer Operator', 'Data Entry Operator', 'Office Assistant'], tags: ['computer', 'IT', 'typing', 'data entry', 'office'], sourceName: 'NSDC', verified: true },
  { title: 'Mason (General)', titleHi: 'राजमिस्त्री (सामान्य)', sector: 'Construction', nsqfLevel: 3, minEducation: 'none', durationHours: 400, jobRoles: ['Mason', 'Construction Worker', 'Bricklayer'], tags: ['masonry', 'construction', 'building', 'eet', 'cement'], sourceName: 'NSDC', verified: true },
  { title: 'Food Processing (Pickle & Papad Making)', titleHi: 'खाद्य प्रसंस्करण (अचार एवं पापड़)', sector: 'Food Processing', nsqfLevel: 3, minEducation: '5th', durationHours: 250, jobRoles: ['Food Processor', 'Home-based Food Business Owner'], tags: ['food', 'pickle', 'papad', 'cooking', 'achar', 'khana'], sourceName: 'NSDC', verified: true },
  { title: 'Two Wheeler Mechanic', titleHi: 'दोपहिया वाहन मैकेनिक', sector: 'Automotive', nsqfLevel: 3, minEducation: '8th', durationHours: 400, jobRoles: ['Bike Mechanic', 'Two-Wheeler Service Technician'], tags: ['mechanic', 'bike', 'motorcycle', 'vehicle', 'repair', 'gaadi'], sourceName: 'NSDC', verified: true },
  { title: 'Handloom Weaver', titleHi: 'हथकरघा बुनकर', sector: 'Textile & Handloom', nsqfLevel: 3, minEducation: 'none', durationHours: 500, jobRoles: ['Weaver', 'Handloom Worker', 'Textile Artisan'], tags: ['weaving', 'handloom', 'textile', 'bunai', 'cloth'], sourceName: 'NSDC', verified: true },

  // New 18
  { title: 'Retail Sales Associate', titleHi: 'रिटेल सेल्स एसोसिएट', sector: 'Retail', nsqfLevel: 4, minEducation: '10th', durationHours: 280, jobRoles: ['Sales Executive', 'Shop Assistant'], tags: ['sales', 'shop', 'retail', 'dukaan'], sourceName: 'NSDC', verified: true },
  { title: 'Domestic Data Entry Operator', titleHi: 'डेटा एंट्री ऑपरेटर', sector: 'IT-ITeS', nsqfLevel: 4, minEducation: '10th', durationHours: 400, jobRoles: ['Data Entry Operator'], tags: ['computer', 'typing', 'data entry'], sourceName: 'NSDC', verified: true },
  { title: 'Customer Care Executive', titleHi: 'कस्टमर केयर एक्जीक्यूटिव', sector: 'Telecom', nsqfLevel: 4, minEducation: '12th', durationHours: 400, jobRoles: ['Call Center Agent', 'BPO Executive'], tags: ['call center', 'bpo', 'telecaller', 'customer service'], sourceName: 'NSDC', verified: true },
  { title: 'Welder (Gas & Electric)', titleHi: 'वेल्डर (गैस और इलेक्ट्रिक)', sector: 'Capital Goods', nsqfLevel: 3, minEducation: '8th', durationHours: 350, jobRoles: ['Welder', 'Fabricator'], tags: ['welding', 'iron', 'loha', 'fabrication'], sourceName: 'NSDC', verified: true },
  { title: 'General Duty Assistant (Healthcare)', titleHi: 'नर्सिंग सहायक (जनरल ड्यूटी)', sector: 'Healthcare', nsqfLevel: 4, minEducation: '10th', durationHours: 600, jobRoles: ['Ward Boy', 'Nursing Assistant'], tags: ['hospital', 'nurse', 'medical', 'clinic', 'health'], sourceName: 'NSDC', verified: true },
  { title: 'Solar PV Installer (Suryamitra)', titleHi: 'सोलर पैनल इंस्टॉलर', sector: 'Green Jobs', nsqfLevel: 4, minEducation: '10th', durationHours: 300, jobRoles: ['Solar Technician', 'Installer'], tags: ['solar', 'energy', 'bijli', 'sun'], sourceName: 'NSDC', verified: true },
  { title: 'Carpentry (General)', titleHi: 'बढ़ई (सामान्य)', sector: 'Furniture & Fittings', nsqfLevel: 3, minEducation: 'none', durationHours: 400, jobRoles: ['Carpenter', 'Woodworker'], tags: ['carpenter', 'wood', 'furniture', 'badhai', 'lakdi'], sourceName: 'NSDC', verified: true },
  { title: 'Tractor Mechanic', titleHi: 'ट्रैक्टर मैकेनिक', sector: 'Automotive', nsqfLevel: 4, minEducation: '8th', durationHours: 450, jobRoles: ['Agricultural Machinery Mechanic'], tags: ['mechanic', 'tractor', 'farming', 'repair'], sourceName: 'NSDC', verified: true },
  { title: 'Mushroom Grower', titleHi: 'मशरूम उत्पादक', sector: 'Agriculture', nsqfLevel: 3, minEducation: 'none', durationHours: 200, jobRoles: ['Mushroom Farmer'], tags: ['farming', 'mushroom', 'agriculture'], sourceName: 'NSDC', verified: true },
  { title: 'Field Technician - Air Conditioner', titleHi: 'एसी मैकेनिक', sector: 'Electronics & Hardware', nsqfLevel: 4, minEducation: '8th', durationHours: 350, jobRoles: ['AC Mechanic', 'Cooling Technician'], tags: ['ac', 'fridge', 'repair', 'mechanic'], sourceName: 'NSDC', verified: true },
  { title: 'Hand Embroiderer', titleHi: 'हाथ की कढ़ाई करने वाला', sector: 'Apparel', nsqfLevel: 3, minEducation: 'none', durationHours: 250, jobRoles: ['Embroidery Artisan'], tags: ['embroidery', 'kadhai', 'fashion', 'sewing'], sourceName: 'NSDC', verified: true },
  { title: 'CCTV Installation Technician', titleHi: 'सीसीटीवी इंस्टॉलेशन तकनीशियन', sector: 'Electronics', nsqfLevel: 4, minEducation: '10th', durationHours: 300, jobRoles: ['CCTV Technician'], tags: ['cctv', 'camera', 'security', 'installation'], sourceName: 'NSDC', verified: true },
  { title: 'Housekeeping Attendant', titleHi: 'हाउसकीपिंग अटेंडेंट', sector: 'Tourism & Hospitality', nsqfLevel: 3, minEducation: '5th', durationHours: 250, jobRoles: ['Cleaner', 'Hotel Staff'], tags: ['hotel', 'cleaning', 'safai', 'housekeeping'], sourceName: 'NSDC', verified: true },
  { title: 'Security Guard', titleHi: 'सुरक्षा गार्ड', sector: 'Private Security', nsqfLevel: 3, minEducation: '8th', durationHours: 160, jobRoles: ['Security Guard', 'Watchman'], tags: ['security', 'guard', 'watchman', 'chowkidaar'], sourceName: 'NSDC', verified: true },
  { title: 'Driver (Light Motor Vehicle)', titleHi: 'ड्राइवर (कार)', sector: 'Logistics', nsqfLevel: 3, minEducation: '8th', durationHours: 300, jobRoles: ['Taxi Driver', 'Chauffeur'], tags: ['driving', 'car', 'driver', 'transport'], sourceName: 'NSDC', verified: true },
  { title: 'Animal Health Worker', titleHi: 'पशु स्वास्थ्य कार्यकर्ता', sector: 'Agriculture', nsqfLevel: 4, minEducation: '10th', durationHours: 400, jobRoles: ['Veterinary Assistant'], tags: ['animal', 'cow', 'vet', 'pashu', 'health'], sourceName: 'NSDC', verified: true },
  { title: 'Bakery Artisan', titleHi: 'बेकरी कारीगर', sector: 'Food Processing', nsqfLevel: 3, minEducation: '5th', durationHours: 300, jobRoles: ['Baker'], tags: ['bakery', 'bread', 'cake', 'food', 'cooking'], sourceName: 'NSDC', verified: true },
  { title: 'Baking & Confectionery', titleHi: 'बेकिंग और कन्फेक्शनरी', sector: 'Tourism & Hospitality', nsqfLevel: 4, minEducation: '8th', durationHours: 350, jobRoles: ['Pastry Chef'], tags: ['baking', 'sweet', 'food'], sourceName: 'NSDC', verified: true },

  // Additional 20 (Total 50)
  { title: 'CNC Operator Turning', titleHi: 'सीएनसी ऑपरेटर', sector: 'Capital Goods', nsqfLevel: 4, minEducation: '10th', durationHours: 300, jobRoles: ['Machine Operator'], tags: ['cnc', 'machine', 'factory'], sourceName: 'NSDC', verified: true },
  { title: 'Phlebotomist', titleHi: 'रक्त निकालने वाला (फ्लेबोटोमिस्ट)', sector: 'Healthcare', nsqfLevel: 4, minEducation: '12th', durationHours: 400, jobRoles: ['Lab Technician'], tags: ['blood', 'lab', 'medical', 'test'], sourceName: 'NSDC', verified: true },
  { title: 'Data Associate', titleHi: 'डेटा एसोसिएट', sector: 'IT-ITeS', nsqfLevel: 4, minEducation: '12th', durationHours: 400, jobRoles: ['Data Analyst', 'Data Operator'], tags: ['computer', 'data', 'office'], sourceName: 'NSDC', verified: true },
  { title: 'Fitter - Fabrication', titleHi: 'फिटर - फैब्रिकेशन', sector: 'Capital Goods', nsqfLevel: 3, minEducation: '8th', durationHours: 350, jobRoles: ['Fitter'], tags: ['iron', 'welding', 'factory'], sourceName: 'NSDC', verified: true },
  { title: 'Sales Executive (FMCG)', titleHi: 'सेल्स एग्जीक्यूटिव (FMCG)', sector: 'Retail', nsqfLevel: 4, minEducation: '10th', durationHours: 300, jobRoles: ['Field Sales Representative'], tags: ['sales', 'field work', 'marketing'], sourceName: 'NSDC', verified: true },
  { title: 'Pesticide and Fertilizer Applicator', titleHi: 'कीटनाशक और उर्वरक प्रयोगकर्ता', sector: 'Agriculture', nsqfLevel: 3, minEducation: '5th', durationHours: 200, jobRoles: ['Agriculture Worker'], tags: ['farming', 'spray', 'agriculture'], sourceName: 'NSDC', verified: true },
  { title: 'Bridal Makeup Artist', titleHi: 'दुल्हन मेकअप आर्टिस्ट', sector: 'Beauty & Wellness', nsqfLevel: 4, minEducation: '8th', durationHours: 400, jobRoles: ['Makeup Artist'], tags: ['beauty', 'makeup', 'wedding'], sourceName: 'NSDC', verified: true },
  { title: 'Courier Delivery Executive', titleHi: 'कूरियर डिलीवरी बॉय', sector: 'Logistics', nsqfLevel: 3, minEducation: '8th', durationHours: 250, jobRoles: ['Delivery Boy'], tags: ['delivery', 'driving', 'bike'], sourceName: 'NSDC', verified: true },
  { title: 'Tour Guide', titleHi: 'टूर गाइड', sector: 'Tourism & Hospitality', nsqfLevel: 4, minEducation: '10th', durationHours: 400, jobRoles: ['Local Guide'], tags: ['tourism', 'travel', 'guide'], sourceName: 'NSDC', verified: true },
  { title: 'Accounts Assistant', titleHi: 'अकाउंट्स असिस्टेंट', sector: 'BFSI', nsqfLevel: 4, minEducation: '12th', durationHours: 500, jobRoles: ['Accountant', 'Clerk'], tags: ['finance', 'maths', 'office'], sourceName: 'NSDC', verified: true },
  { title: 'Microfinance Executive', titleHi: 'माइक्रोफाइनेंस एग्जीक्यूटिव', sector: 'BFSI', nsqfLevel: 4, minEducation: '12th', durationHours: 300, jobRoles: ['Loan Officer'], tags: ['bank', 'loan', 'field work'], sourceName: 'NSDC', verified: true },
  { title: 'Front Office Associate', titleHi: 'फ्रंट ऑफिस एसोसिएट', sector: 'Tourism & Hospitality', nsqfLevel: 4, minEducation: '12th', durationHours: 300, jobRoles: ['Receptionist'], tags: ['hotel', 'reception', 'office'], sourceName: 'NSDC', verified: true },
  { title: 'DTH Set Top Box Installer', titleHi: 'डीटीएच सेट टॉप बॉक्स इंस्टॉलर', sector: 'Electronics', nsqfLevel: 3, minEducation: '8th', durationHours: 250, jobRoles: ['Dish Technician'], tags: ['tv', 'dish', 'electronics'], sourceName: 'NSDC', verified: true },
  { title: 'Bicycle Mechanic', titleHi: 'साइकिल मैकेनिक', sector: 'Automotive', nsqfLevel: 3, minEducation: 'none', durationHours: 200, jobRoles: ['Mechanic'], tags: ['bicycle', 'repair', 'mechanic'], sourceName: 'NSDC', verified: true },
  { title: 'Beekeeper', titleHi: 'मधुमक्खी पालक', sector: 'Agriculture', nsqfLevel: 3, minEducation: 'none', durationHours: 200, jobRoles: ['Honey Farmer'], tags: ['farming', 'honey', 'bees'], sourceName: 'NSDC', verified: true },
  { title: 'Warehouse Packer', titleHi: 'वेयरहाउस पैकर', sector: 'Logistics', nsqfLevel: 3, minEducation: '5th', durationHours: 200, jobRoles: ['Packer'], tags: ['logistics', 'warehouse', 'packing'], sourceName: 'NSDC', verified: true },
  { title: 'Barber / Hair Stylist', titleHi: 'नाई / हेयर स्टाइलिस्ट', sector: 'Beauty & Wellness', nsqfLevel: 3, minEducation: 'none', durationHours: 300, jobRoles: ['Barber'], tags: ['hair', 'salon', 'barber'], sourceName: 'NSDC', verified: true },
  { title: 'Plumbing Foreman', titleHi: 'प्लंबिंग फोरमैन', sector: 'Construction', nsqfLevel: 4, minEducation: '10th', durationHours: 400, jobRoles: ['Plumber Supervisor'], tags: ['plumbing', 'construction', 'supervisor'], sourceName: 'NSDC', verified: true },
  { title: 'Yoga Instructor', titleHi: 'योग प्रशिक्षक', sector: 'Beauty & Wellness', nsqfLevel: 4, minEducation: '10th', durationHours: 400, jobRoles: ['Yoga Teacher'], tags: ['yoga', 'health', 'wellness'], sourceName: 'NSDC', verified: true },
  { title: 'Jam, Jelly and Ketchup Processing Technician', titleHi: 'जैम और जेली मेकर', sector: 'Food Processing', nsqfLevel: 3, minEducation: '8th', durationHours: 300, jobRoles: ['Food Processor'], tags: ['food', 'cooking', 'factory'], sourceName: 'NSDC', verified: true }
];

const livelihoods = [
  // Previous 10 with explicit cost and support note
  { title: 'Village Level Tailoring Business', titleHi: 'गाँव स्तरीय सिलाई व्यवसाय', sector: 'Apparel', type: 'self-employment', minEducation: '5th', requiredSkills: ['tailoring', 'sewing'], demandSignal: 'high', startupCostRange: '₹10,000–₹50,000', supportNote: 'PM-AJAY ya bank loan ke options ke liye local officer se baat karein.', description: 'Start a small tailoring shop in your village. High demand for blouse, petticoat, and school uniform stitching.' },
  { title: 'Mobile Repair Shop', titleHi: 'मोबाइल रिपेयर दुकान', sector: 'Electronics', type: 'self-employment', minEducation: '10th', requiredSkills: ['mobile repair', 'electronics'], demandSignal: 'high', startupCostRange: '₹20,000–₹60,000', supportNote: 'Mudra loan ke antargat aavedan kar sakte hain.', description: 'Open a mobile phone repair shop. Every village and town needs one.' },
  { title: 'Small Dairy Farm', titleHi: 'छोटी डेयरी फार्म', sector: 'Agriculture', type: 'self-employment', minEducation: 'none', requiredSkills: ['cattle care', 'dairy', 'animal husbandry'], demandSignal: 'high', startupCostRange: '₹50,000–₹1,50,000', supportNote: 'Pashupalan vibhag se subsidy prapt karne ke liye sampark karein.', description: 'Start with 2-3 cows or buffaloes. Sell milk to local collection centres.' },
  { title: 'Construction Labour (Skilled)', titleHi: 'कुशल निर्माण श्रमिक', sector: 'Construction', type: 'wage', minEducation: 'none', requiredSkills: ['masonry', 'construction'], demandSignal: 'high', startupCostRange: '₹0–₹5,000 (Tools)', supportNote: 'NCS portal par apna registration zarur karwayein.', description: 'Skilled masons earn ₹600-800/day. PMAY housing scheme creating huge demand.' },
  { title: 'Beauty Parlour at Home', titleHi: 'घर पर ब्यूटी पार्लर', sector: 'Beauty & Wellness', type: 'self-employment', minEducation: '8th', requiredSkills: ['beauty', 'makeup', 'grooming'], demandSignal: 'medium', startupCostRange: '₹15,000–₹40,000', supportNote: 'Sthaniye mahila samuh (SHG) se jud kar shuru kar sakti hain.', description: 'Start a small beauty parlour from home. Low investment, growing demand in rural areas.' },
  { title: 'Electrician Work', titleHi: 'बिजली मिस्त्री का काम', sector: 'Electronics', type: 'wage', minEducation: '8th', requiredSkills: ['electrical', 'wiring'], demandSignal: 'high', startupCostRange: '₹5,000–₹15,000 (Toolkit)', supportNote: 'Local contractors ke saath kaam shuru kar sakte hain.', description: 'House wiring, appliance repair. Every new house needs an electrician.' },
  { title: 'Organic Vegetable Farming', titleHi: 'जैविक सब्जी की खेती', sector: 'Agriculture', type: 'self-employment', minEducation: 'none', requiredSkills: ['farming', 'agriculture'], demandSignal: 'high', startupCostRange: '₹5,000–₹20,000', supportNote: 'Krishi Vigyan Kendra (KVK) se margdarshan lein.', description: 'Grow organic vegetables and sell at local mandis or to urban buyers via WhatsApp.' },
  { title: 'Pickle & Papad Business', titleHi: 'अचार एवं पापड़ का व्यवसाय', sector: 'Food Processing', type: 'self-employment', minEducation: '5th', requiredSkills: ['cooking', 'food processing'], demandSignal: 'medium', startupCostRange: '₹2,000–₹10,000', supportNote: 'FSSAI registration avashyak hai, adhikari se sampark karein.', description: 'Make and sell homemade pickles, papad, and other food items. SHG groups can help scale.' },
  { title: 'Data Entry / Computer Operator', titleHi: 'डाटा एंट्री / कंप्यूटर ऑपरेटर', sector: 'IT-ITeS', type: 'wage', minEducation: '10th', requiredSkills: ['computer', 'typing', 'data entry'], demandSignal: 'medium', startupCostRange: '₹0 (N/A)', supportNote: 'NCS par current openings check karein ya local CSC par puchein.', description: 'Work at CSC centres, banks, or government offices as a computer operator.' },
  { title: 'Two Wheeler Repair Workshop', titleHi: 'दोपहिया वाहन रिपेयर वर्कशॉप', sector: 'Automotive', type: 'self-employment', minEducation: '8th', requiredSkills: ['mechanic', 'vehicle repair'], demandSignal: 'high', startupCostRange: '₹30,000–₹80,000', supportNote: 'PM-AJAY grant ya bank loan ke liye jila adhikari se milein.', description: 'Open a bike/scooter repair shop. Growing demand with increasing two-wheeler ownership.' },

  // New 20
  { title: 'CSC (Common Service Centre) Operator', titleHi: 'जन सेवा केंद्र संचालक', sector: 'IT', type: 'self-employment', minEducation: '10th', requiredSkills: ['computer', 'internet'], demandSignal: 'high', description: 'Open a CSC to provide digital services like PAN, Aadhaar, and banking to villagers.' },
  { title: 'Poultry Farm', titleHi: 'मुर्गी पालन', sector: 'Agriculture', type: 'self-employment', minEducation: 'none', requiredSkills: ['farming', 'poultry'], demandSignal: 'high', description: 'Start a small broiler or layer poultry farm. Quick returns on investment.' },
  { title: 'Goat Farming', titleHi: 'बकरी पालन', sector: 'Agriculture', type: 'self-employment', minEducation: 'none', requiredSkills: ['animal husbandry'], demandSignal: 'high', description: 'Goat farming requires very low investment and provides excellent meat and milk income.' },
  { title: 'Hospital Ward Attendant', titleHi: 'अस्पताल वार्ड बॉय/आया', sector: 'Healthcare', type: 'wage', minEducation: '8th', requiredSkills: ['nursing', 'cleaning'], demandSignal: 'high', description: 'Work in nearby private hospitals or PHCs helping patients.' },
  { title: 'Security Guard', titleHi: 'सुरक्षा गार्ड', sector: 'Security', type: 'wage', minEducation: '8th', requiredSkills: ['security'], demandSignal: 'high', description: 'High demand in cities, factories, and residential societies.' },
  { title: 'Ola/Uber/Taxi Driver', titleHi: 'टैक्सी ड्राइवर', sector: 'Logistics', type: 'self-employment', minEducation: '8th', requiredSkills: ['driving'], demandSignal: 'high', description: 'Drive a taxi or commercial vehicle in nearby towns.' },
  { title: 'Delivery Partner (Amazon/Zomato)', titleHi: 'डिलीवरी बॉय', sector: 'Logistics', type: 'wage', minEducation: '8th', requiredSkills: ['driving', 'bike'], demandSignal: 'high', description: 'Work as a delivery partner for e-commerce or food delivery apps.' },
  { title: 'AC & Fridge Repair Shop', titleHi: 'एसी और फ्रिज रिपेयर', sector: 'Electronics', type: 'self-employment', minEducation: '8th', requiredSkills: ['ac repair', 'electronics'], demandSignal: 'medium', description: 'Great summer business. Needs technical training.' },
  { title: 'Welding Fabrication Shop', titleHi: 'वेल्डिंग की दुकान', sector: 'Capital Goods', type: 'self-employment', minEducation: '8th', requiredSkills: ['welding', 'fabrication'], demandSignal: 'medium', description: 'Make grills, gates, and agricultural tools for local demand.' },
  { title: 'Plumbing Services', titleHi: 'प्लंबिंग सेवाएं', sector: 'Construction', type: 'self-employment', minEducation: '5th', requiredSkills: ['plumbing'], demandSignal: 'high', description: 'Provide on-call plumbing repair services for households and new buildings.' },
  { title: 'Mushroom Cultivation', titleHi: 'मशरूम की खेती', sector: 'Agriculture', type: 'self-employment', minEducation: 'none', requiredSkills: ['farming'], demandSignal: 'medium', description: 'Can be done indoors with very little space. Sells at good profit.' },
  { title: 'Carpentry / Furniture Shop', titleHi: 'फर्नीचर की दुकान (बढ़ई)', sector: 'Furniture', type: 'self-employment', minEducation: 'none', requiredSkills: ['carpentry', 'woodwork'], demandSignal: 'medium', description: 'Make and repair beds, doors, and tables for villagers.' },
  { title: 'BPO / Call Center Executive', titleHi: 'कॉल सेंटर एग्जीक्यूटिव', sector: 'Telecom', type: 'wage', minEducation: '12th', requiredSkills: ['speaking', 'computer'], demandSignal: 'high', description: 'Work in customer support. Requires good communication in Hindi or English.' },
  { title: 'Retail Shop Assistant', titleHi: 'दुकान सहायक', sector: 'Retail', type: 'wage', minEducation: '8th', requiredSkills: ['sales', 'communication'], demandSignal: 'high', description: 'Work as a salesman at clothing, grocery, or hardware stores.' },
  { title: 'Kirana / Grocery Store', titleHi: 'किराना दुकान', sector: 'Retail', type: 'self-employment', minEducation: 'none', requiredSkills: ['sales', 'basic math'], demandSignal: 'high', description: 'Open a general store in the village. Very stable income source.' },
  { title: 'Bakery Shop', titleHi: 'बेकरी की दुकान', sector: 'Food Processing', type: 'self-employment', minEducation: '5th', requiredSkills: ['baking', 'cooking'], demandSignal: 'medium', description: 'Bake and sell biscuits, cakes, and fresh breads locally.' },
  { title: 'Housemaid / Cook', titleHi: 'घरेलू सहायिका / कुक', sector: 'Domestic Help', type: 'wage', minEducation: 'none', requiredSkills: ['cleaning', 'cooking'], demandSignal: 'high', description: 'Work in urban households providing cleaning and cooking services.' },
  { title: 'Solar Panel Maintenance', titleHi: 'सोलर पैनल रखरखाव', sector: 'Green Jobs', type: 'wage', minEducation: '10th', requiredSkills: ['solar', 'electrical'], demandSignal: 'medium', description: 'Maintain and install solar pumps and rooftop panels.' },
  { title: 'Handicraft / Embroidery Business', titleHi: 'हस्तशिल्प / कढ़ाई व्यवसाय', sector: 'Apparel', type: 'self-employment', minEducation: 'none', requiredSkills: ['embroidery', 'craft'], demandSignal: 'medium', description: 'Make and sell embroidered clothes or bamboo crafts.' },
  { title: 'Tractor Mechanic', titleHi: 'ट्रैक्टर मैकेनिक', sector: 'Automotive', type: 'self-employment', minEducation: '8th', requiredSkills: ['mechanic'], demandSignal: 'medium', startupCostRange: '₹20,000–₹50,000', supportNote: 'Tools lene ke liye bank loan avashyak hai.', description: 'Repair tractors and farm machinery in rural areas.' },

  // Additional 20 (Total 50)
  { title: 'E-Rickshaw Driver', titleHi: 'ई-रिक्शा चालक', sector: 'Logistics', type: 'self-employment', minEducation: 'none', requiredSkills: ['driving'], demandSignal: 'high', startupCostRange: '₹30,000–₹50,000 (Downpayment)', supportNote: 'PM E-Drive scheme ke tehat subsidy lein.', description: 'Drive an E-rickshaw in semi-urban or town areas for stable daily income.' },
  { title: 'Flour Mill (Atta Chakki)', titleHi: 'आटा चक्की', sector: 'Food Processing', type: 'self-employment', minEducation: 'none', requiredSkills: ['machine operation'], demandSignal: 'high', startupCostRange: '₹40,000–₹1,00,000', supportNote: 'Mudra loan se machine khareed sakte hain.', description: 'Open a local flour mill in the village.' },
  { title: 'Tea Stall / Snack Center', titleHi: 'चाय की दुकान', sector: 'Tourism & Hospitality', type: 'self-employment', minEducation: 'none', requiredSkills: ['cooking', 'sales'], demandSignal: 'high', startupCostRange: '₹10,000–₹25,000', supportNote: 'Sthaniye nagar nigam se permission lein.', description: 'A highly profitable daily cash business in busy areas.' },
  { title: 'Mobile Fast Food Cart', titleHi: 'फास्ट फूड ठेला', sector: 'Tourism & Hospitality', type: 'self-employment', minEducation: 'none', requiredSkills: ['cooking'], demandSignal: 'high', startupCostRange: '₹15,000–₹40,000', supportNote: 'FSSAI ka basic registration zaroori hai.', description: 'Sell chowmein, momos, or local street food in the evenings.' },
  { title: 'Fish Farming (Aquaculture)', titleHi: 'मछली पालन', sector: 'Agriculture', type: 'self-employment', minEducation: 'none', requiredSkills: ['farming'], demandSignal: 'medium', startupCostRange: '₹50,000–₹2,00,000', supportNote: 'PM Matsya Sampada Yojana ke tahat aavedan karein.', description: 'Use a local pond to breed and sell fish in the wholesale market.' },
  { title: 'Beekeeping (Apiculture)', titleHi: 'मधुमक्खी पालन', sector: 'Agriculture', type: 'self-employment', minEducation: 'none', requiredSkills: ['farming'], demandSignal: 'medium', startupCostRange: '₹20,000–₹60,000', supportNote: 'Khadi and Village Industries Commission (KVIC) se subsidy milti hai.', description: 'Produce pure honey and sell at premium rates.' },
  { title: 'Hardware and Sanitary Shop', titleHi: 'हार्डवेयर की दुकान', sector: 'Retail', type: 'self-employment', minEducation: '8th', requiredSkills: ['sales'], demandSignal: 'high', startupCostRange: '₹1,00,000–₹3,00,000', supportNote: 'Bank loan zaroori ho sakta hai.', description: 'Sell construction materials, pipes, and fittings.' },
  { title: 'Medical Store (Pharmacy)', titleHi: 'मेडिकल स्टोर', sector: 'Retail', type: 'self-employment', minEducation: '12th', requiredSkills: ['pharmacy', 'sales'], demandSignal: 'high', startupCostRange: '₹1,50,000–₹5,00,000', supportNote: 'D-Pharma/B-Pharma degree aur license anivarya hai.', description: 'Open a pharmacy if you or a partner has a pharmacy license.' },
  { title: 'Tiffin Service', titleHi: 'टिफिन सर्विस', sector: 'Food Processing', type: 'self-employment', minEducation: 'none', requiredSkills: ['cooking'], demandSignal: 'high', startupCostRange: '₹5,000–₹15,000', supportNote: 'FSSAI license zaroori hai.', description: 'Provide daily homemade meals to students and working professionals.' },
  { title: 'Photocopy & Stationery Shop', titleHi: 'फोटोकॉपी और स्टेशनरी', sector: 'Retail', type: 'self-employment', minEducation: '8th', requiredSkills: ['computer', 'sales'], demandSignal: 'medium', startupCostRange: '₹50,000–₹1,20,000', supportNote: 'School ya college ke pass kholne पर accha chalega.', description: 'Print documents, sell notebooks, pens, and school supplies.' },
  { title: 'Laundry & Dry Cleaning', titleHi: 'लॉन्ड्री / कपड़े धोना और प्रेस', sector: 'Apparel', type: 'self-employment', minEducation: 'none', requiredSkills: ['cleaning', 'ironing'], demandSignal: 'high', startupCostRange: '₹5,000–₹30,000', supportNote: 'Mudra shishu loan ka labh lein.', description: 'Provide washing and ironing services in residential areas.' },
  { title: 'Car Wash Center', titleHi: 'कार वॉश सेंटर', sector: 'Automotive', type: 'self-employment', minEducation: 'none', requiredSkills: ['cleaning'], demandSignal: 'high', startupCostRange: '₹30,000–₹80,000', supportNote: 'Pani ka connection aur machine zaroori hai.', description: 'Wash cars and bikes. Very high margins on weekends.' },
  { title: 'Bicycle Repair Shop', titleHi: 'साइकिल रिपेयर', sector: 'Automotive', type: 'self-employment', minEducation: 'none', requiredSkills: ['mechanic'], demandSignal: 'medium', startupCostRange: '₹5,000–₹15,000', supportNote: 'Chhoti punji से shuru kiya ja sakta hai.', description: 'Repair cycles in a village or town market.' },
  { title: 'Tent House / Decorator', titleHi: 'टेंट हाउस', sector: 'Tourism & Hospitality', type: 'self-employment', minEducation: 'none', requiredSkills: ['decoration'], demandSignal: 'high', startupCostRange: '₹1,00,000–₹5,00,000', supportNote: 'Shadiyon ke season mein bohot demand rehti hai.', description: 'Provide tents, chairs, and decoration for weddings and events.' },
  { title: 'Garment / Clothes Shop', titleHi: 'कपड़े की दुकान', sector: 'Retail', type: 'self-employment', minEducation: '8th', requiredSkills: ['sales'], demandSignal: 'high', startupCostRange: '₹1,00,000–₹3,00,000', supportNote: 'Bank loan le sakte hain.', description: 'Sell daily wear, unstitched fabric, and hosiery.' },
  { title: 'Papad & Namkeen Manufacturing', titleHi: 'पापड़ और नमकीन निर्माण', sector: 'Food Processing', type: 'self-employment', minEducation: '5th', requiredSkills: ['cooking'], demandSignal: 'medium', startupCostRange: '₹20,000–₹50,000', supportNote: 'FSSAI license aur packaging machinery avashyak.', description: 'Make local snacks and supply to nearby kirana shops.' },
  { title: 'DJ Sound System Service', titleHi: 'डीजे साउंड सिस्टम', sector: 'Tourism & Hospitality', type: 'self-employment', minEducation: '8th', requiredSkills: ['electronics'], demandSignal: 'medium', startupCostRange: '₹1,00,000–₹3,00,000', supportNote: 'Event management companies se sampark banayein.', description: 'Provide sound systems for local weddings and functions.' },
  { title: 'Insurance Agent', titleHi: 'बीमा एजेंट (LIC/General)', sector: 'BFSI', type: 'self-employment', minEducation: '10th', requiredSkills: ['sales', 'communication'], demandSignal: 'medium', startupCostRange: '₹2,000 (Exam Fees)', supportNote: 'IRDAI exam pass karna zaroori hai.', description: 'Sell life and health insurance policies on commission basis.' },
  { title: 'RO Water Purifier Service', titleHi: 'आरओ वाटर रिपेयर', sector: 'Electronics', type: 'self-employment', minEducation: '8th', requiredSkills: ['plumbing', 'repair'], demandSignal: 'high', startupCostRange: '₹10,000–₹25,000', supportNote: 'Local hardware store se sampark rakhein.', description: 'Install and repair RO water purifiers in homes.' },
  { title: 'Agriculture Machinery Rental', titleHi: 'कृषि यंत्र किराए पर देना', sector: 'Agriculture', type: 'self-employment', minEducation: 'none', requiredSkills: ['farming', 'mechanic'], demandSignal: 'high', startupCostRange: '₹2,00,000–₹10,000,000', supportNote: 'Krishi vibhag se custom hiring center ke liye subsidy milti hai.', description: 'Rent out tractors, rotavators, and harvesters to other farmers.' }
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Force clear everything and re-insert the full list
    await Course.deleteMany({});
    await Livelihood.deleteMany({});
    
    await Course.insertMany(courses);
    console.log(`✅ Seeded ${courses.length} courses`);

    await Livelihood.insertMany(livelihoods);
    console.log(`✅ Seeded ${livelihoods.length} livelihoods`);

    console.log('\n🎉 Database successfully seeded with 30 courses and 30 livelihoods!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err);
    process.exit(1);
  }
}

seed();
